### ISSUE TITLE
Whitelist/Blacklist in Inlines

### ISSUE THREAD

**Issue by typeshige** [arthanson/django-genericadmin#20] opened 2014-07-08 16:55 UTC
I'm trying to specify a whitelist but it seems to be ignored.

    class ContentInline(StackedInlineWithGeneric):
        model = Content
        extra = 0
        content_type_whitelist = (...,)

**Comment by arthanson** [comment] 2016-04-07 02:42
not a bug, closing

**Closed by arthanson** 2016-04-07 02:42 UTC
